# Row pins
set_property PACKAGE_PIN G3 [get_ports {row[0]}]
set_property PACKAGE_PIN G2 [get_ports {row[1]}]
set_property PACKAGE_PIN H1 [get_ports {row[2]}]
set_property PACKAGE_PIN J2 [get_ports {row[3]}]
set_property PACKAGE_PIN K2 [get_ports {row[4]}]
set_property PACKAGE_PIN L2 [get_ports {row[5]}]
set_property PACKAGE_PIN H2 [get_ports {row[6]}]
set_property PACKAGE_PIN J1 [get_ports {row[7]}]

# Column pins
set_property PACKAGE_PIN N1 [get_ports {col[0]}]
set_property PACKAGE_PIN N2 [get_ports {col[1]}]
set_property PACKAGE_PIN M1 [get_ports {col[2]}]
set_property PACKAGE_PIN M2 [get_ports {col[3]}]
set_property PACKAGE_PIN M3 [get_ports {col[4]}]
set_property PACKAGE_PIN L3 [get_ports {col[5]}]
set_property PACKAGE_PIN K3 [get_ports {col[6]}]
set_property PACKAGE_PIN J3 [get_ports {col[7]}]

# Button and clock pins
set_property PACKAGE_PIN U17 [get_ports btnBottom]
set_property PACKAGE_PIN W19 [get_ports btnLeft]
set_property PACKAGE_PIN T17 [get_ports btnRight]
set_property PACKAGE_PIN T18 [get_ports btnTop]
set_property PACKAGE_PIN U18 [get_ports reset]
set_property PACKAGE_PIN W5 [get_ports clk]


# I/O standards
set_property IOSTANDARD LVCMOS18 [get_ports {row[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {row[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports {col[0]}]
set_property IOSTANDARD LVCMOS18 [get_ports {col[1]}]
set_property IOSTANDARD LVCMOS18 [get_ports {col[2]}]
set_property IOSTANDARD LVCMOS18 [get_ports {col[3]}]
set_property IOSTANDARD LVCMOS18 [get_ports {col[4]}]
set_property IOSTANDARD LVCMOS18 [get_ports {col[5]}]
set_property IOSTANDARD LVCMOS18 [get_ports {col[6]}]
set_property IOSTANDARD LVCMOS18 [get_ports {col[7]}]
set_property IOSTANDARD LVCMOS18 [get_ports btnBottom]
set_property IOSTANDARD LVCMOS18 [get_ports btnLeft]
set_property IOSTANDARD LVCMOS18 [get_ports btnRight]
set_property IOSTANDARD LVCMOS18 [get_ports btnTop]
set_property IOSTANDARD LVCMOS18 [get_ports clk]
set_property IOSTANDARD LVCMOS18 [get_ports reset]

set_property -dict { PACKAGE_PIN U16   IOSTANDARD LVCMOS18 } [get_ports {Q_in[0]}]
set_property -dict { PACKAGE_PIN E19   IOSTANDARD LVCMOS18 } [get_ports {Q_in[1]}]
set_property -dict { PACKAGE_PIN U19   IOSTANDARD LVCMOS18 } [get_ports {Q_in[2]}]
set_property -dict { PACKAGE_PIN V19   IOSTANDARD LVCMOS18 } [get_ports {Q_in[3]}]
set_property -dict { PACKAGE_PIN W18   IOSTANDARD LVCMOS18 } [get_ports {X[0]}]
set_property -dict { PACKAGE_PIN U15   IOSTANDARD LVCMOS18 } [get_ports {X[1]}]
#set_property -dict { PACKAGE_PIN U14   IOSTANDARD LVCMOS18 } [get_ports {Q_out[2]}]
#set_property -dict { PACKAGE_PIN V14   IOSTANDARD LVCMOS18 } [get_ports {Q_out[3]}]
#set_property -dict { PACKAGE_PIN V13   IOSTANDARD LVCMOS18 } [get_ports {X[1]}]
#set_property -dict { PACKAGE_PIN V3    IOSTANDARD LVCMOS18 } [get_ports {X[0]}]
#set_property -dict { PACKAGE_PIN W3    IOSTANDARD LVCMOS33 } [get_ports {led[10]}]
#set_property -dict { PACKAGE_PIN U3    IOSTANDARD LVCMOS33 } [get_ports {led[11]}]
#set_property -dict { PACKAGE_PIN P3    IOSTANDARD LVCMOS33 } [get_ports {led[12]}]
#set_property -dict { PACKAGE_PIN N3    IOSTANDARD LVCMOS33 } [get_ports {led[13]}]
#set_property -dict { PACKAGE_PIN P1    IOSTANDARD LVCMOS33 } [get_ports {led[14]}]
#set_property -dict { PACKAGE_PIN L1    IOSTANDARD LVCMOS33 } [get_ports {led[15]}]

